// common/constants/svg-map.ts
// Updated to use string keys that match original component names
// These keys will be processed by modifySvg function which automatically fetches from AWS using fetchAwsAsset

/**
 * Background SVG map using string keys for AWS asset fetching
 * Keys correspond to original component names (which match AWS SVG filenames without .svg extension)
 */
export const backgroundSvgMap: Record<string, Record<string, string>> = {
  "social-post": {
    wave: "BGPostWave",
    multipleCircles: "BGSocialPostCircle",
    stripes3: "BG3stripes",
    blur_bl_tr: "BGPostSvg4",
    blur_bl: "BGSocialBannerSvg9",
    triangles_tl_br: "BGTriangle_tl_br",
    noise: "BGPostNoise",
    svg8: "BGPostSvg8",
    svg9: "BGPostSvg9",
    svg3: "BGPostSvg3",
    svg12: "BGPostSvg12",
    svg4: "BGPostSvg4",
    svg5: "BGPostSvg5",
    svg7: "BGPostSvg7",
    svg10: "BGPostSvg10",
  },
  "quote-card": {
    wave: "BGPostWave",
    multipleCircles: "BGSocialPostCircle",
    stripes3: "BG3stripes",
    blur_bl_tr: "BGPostSvg4",
    blur_bl: "BGSocialBannerSvg9",
    triangles_tl_br: "BGTriangle_tl_br",
    svg9: "BGPostSvg9",
    svg10: "BGPostSvg10",
    svg11: "BGPostSvg12",
    svg3: "BGPostSvg3",
    svg4: "BGPostSvg4",
    svg5: "BGPostSvg5",
    noise: "BGPostNoise",
    circle: "BGPostSvg7",
    linear: "BGPostSvg5",
    svg8: "BGPostSvg8",
    svg2: "BGPostSvg2",
    svg6: "BGPostSvg6",
  },
  "textimg-post": {
    wave: "BGPostWave",
    multipleCircles: "BGSocialPostCircle",
    stripes3: "BG3stripes",
    blur_bl_tr: "BGPostSvg4",
    blur_bl: "BGSocialBannerSvg9",
    triangles_tl_br: "BGTriangle_tl_br",
    svg9: "BGPostSvg9",
    noise: "BGPostNoise",
    svg10: "BGPostSvg10",
    svg11: "BGPostSvg12",
    svg3: "BGPostSvg3",
    svg4: "BGPostSvg4",
    svg5: "BGPostSvg5",
    circle: "BGPostSvg7",
    linear: "BGPostSvg5",
    svg34: "BGTextImgSvg34",
    featsvg23: "BGFeatSvg23",
    svg8: "BGPostSvg8",
    svg6: "BGTextImgSvg6",
    svg1: "BGTextImgSvg1",
  },
  "featured-post": {
    wave: "BGWave",
    multipleCircles: "BGMultipleCircles",
    stripes3: "BG3stripes",
    blur_bl: "BGSocialBannerSvg9",
    triangles_tl_br: "BGTriangle_tl_br",
    noise: "BGFeatNoise",
    circle: "BGFeatRadialCircle",
    linear: "BGFeatLinearBottom",
    feetsvg11: "BGFeetSvg11",
    feetsvg4: "BGFeatSvg4",
    featsvg23: "BGFeatSvg23",
    featsvg26: "BGFeatSvg26",
    featsvg27: "BGFeatSvg27",
  },
  "mockup-post": {},
  "social-banner": {
    wave: "BGWave",
    multipleCircles: "BGMultipleCircles",
    triangles_tl_br: "BGTriangle_tl_br",
    svg3: "BGPostSvg3",
    noise: "BGNoise",
    circle: "BGRadialCircle",
    linear: "BGLinearLeft",
    svg6: "BGSocialBannerSvg6",
    svg7: "BGSocialBannerSvg7",
    svg9: "BGSocialBannerSvg9",
  },
  "social-carousel": {
    flowPair1A: "BGPostSvg3",
    flowPair1B: "BGPostSvg3",
    flowPair2A: "BGPostSvg5",
    flowPair2B: "BGPostSvg5",
    flowPair3A: "BGPostSvg10",
    flowPair3B: "BGPostSvg10",
    flowPair4A: "BGPostSvg12",
    flowPair4B: "BGPostSvg12",
    flowPair5A: "BGPostSvg8",
    flowPair5B: "BGPostSvg8",
    flowPair6A: "BGPostNoise",
    flowPair6B: "BGPostNoise",
    flowPair7A: "BGCarouselPair7A",
    flowPair7B: "BGCarouselPair7B",
  },
};

/**
 * Headshot backdrop SVG map using string keys for AWS asset fetching
 * Keys correspond to original component names (which match AWS SVG filenames without .svg extension)
 */
export const headshotSvgMap: Record<string, Record<string, string>> = {
  "social-post": {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
  },
  "quote-card": {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
  },
  "textimg-post": {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
  },
  "featured-post": {
    ellipse: "HSFeatEllipse",
    circle: "HSFeatCircle",
    "dotted-rectangle": "HSFeatDottledRectangle",
    stripes: "HSFeatStripes",
  },
  "mockup-post": {},
  "social-banner": {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
    square: "HSSquare",
    fullellipse: "HSFullEllipse",
  },
  "social-cover": {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
  },
  profile: {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
  },
  "social-carousel": {
    ellipse: "HSEllipse",
    circle: "HSCircle",
    "dotted-rectangle": "HSDottedRectangle",
    rectangle: "HSRectangle",
    "small-rectangle": "HSSmallRectangle",
    stripes: "HSStripes",
    square: "HSSquare",
    fullellipse: "HSFullEllipse",
  },
};

export const backdropSvg = {
  center: ["square", "fullellipse", "none"],
  right: [
    "circle",
    "dotted-rectangle",
    "stripes",
    "small-rectangle",
    "ellipse",
    "none",
  ],
};
