export const dynamic = "force-dynamic";

// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instant branding",
  description: "Generated by create next app",
  openGraph: {
    title: "Instant branding | branded LinkedIn presence in minute",
    description:
      "Elevate your LinkedIn presence instantly with branded assets and ready-to-use templates. Get started in minutes!",
    images: [
      {
        url: "https://egovdhnibmbqqjdxtgif.supabase.co/storage/v1/object/public/ib-assets//og.jpg",
        width: 1600,
        height: 840,
        alt: "Instant branding og image ",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Instant branding | branded LinkedIn presence in minute",
    description:
      "Elevate your LinkedIn presence instantly with branded assets and ready-to-use templates. Get started in minutes!",
    images: [
      {
        url: "https://egovdhnibmbqqjdxtgif.supabase.co/storage/v1/object/public/ib-assets//og.jpg",
        width: 1600,
        height: 840,
        alt: "Instant branding og image ",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased h-[100vh] overflow-hidden bg-[#F1F3F3] scrollbar-thin-custom">
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
